"""
NetOps Commander - Professional Network Administration Tool
Authorized use only.
"""

__version__ = "1.3.3"
__app_name__ = "NetOps Commander"

from .constants import (
    APP_NAME,
    APP_VERSION,
    DEFAULT_THEME,
    SUPPORTED_EXPORT_FORMATS,
    ALERT_TYPES,
    MONITOR_INTERVALS,
    SCAN_METHODS,
    DISCOVERY_METHODS,
    DEFAULT_PORTS,
    DEFAULT_SCAN_TIMEOUT,
    DEFAULT_SCAN_CONCURRENCY,
    DEFAULT_PORT_SCAN_TIMEOUT,
    DEFAULT_MONITOR_INTERVAL,
    DEFAULT_MONITOR_MAX_DEVICES,
)
__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "DEFAULT_THEME",
    "SUPPORTED_EXPORT_FORMATS",
    "ALERT_TYPES",
    "MONITOR_INTERVALS",
    "SCAN_METHODS",
    "DISCOVERY_METHODS",
    "DEFAULT_PORTS",
    "DEFAULT_SCAN_TIMEOUT",
    "DEFAULT_SCAN_CONCURRENCY",
    "DEFAULT_PORT_SCAN_TIMEOUT",
    "DEFAULT_MONITOR_INTERVAL",
    "DEFAULT_MONITOR_MAX_DEVICES",
]
